### ISSUE TITLE
Code cleanup meta-issue.

### ISSUE THREAD

**Issue by brenns10** [jpcjr/corvid#23]
Some things we need to clean up in a future "cleanup branch".  Feel free to edit this directly with new additions, so long as you've confirmed that they need to be done.

- [ ] Delete `main/forms/login.py`
- [ ] Delete `main/views/login.py`
- [ ] Delete `main/views/home.py`
- [ ] Refactor `main/(views|models|forms)/__init__.py` so that they import their submodules, and we can clean up imports like so:

  ```python
  from main.models import User, Project, Category
  ```

**Comment by brenns10** [comment]
> - [ ] Remove migrations - can be generated on machine-by-machine basis

On the topic of removing migrations, I belive @jpcjr and I had some good reasons for not doing that, although we can't remember what they were.  So I took that off the list.

> - [ ] More explicit URL capture group names (e.g. `title` -> `project_title` for UpdatePageView)

As for URL capture group names, I think the level of refactoring necessary to support that may be a little much.  Other people can weigh in on that if they disagree, but I'm deleting that from the checklist as well.

I'm also going to add an item fori improving code readability before turning in.
